#!/bin/bash

set -e
set -u

export BACKEND_API_HTTP_PREFIX=https://kcik.chadium.dev:7777
export BACKEND_API_WS_PREFIX=wss://kcik.chadium.dev:7777
export NODE_ENV=production

# Chrome extension.
npm run build
rm -f dist/chrome/chrome.zip
(cd dist/chrome && zip -r chrome.zip .)

# Firefox extension.
npm run build-firefox
rm -f dist/firefox/firefox.zip
(cd dist/firefox && zip -r firefox.zip .)
